name: GitHub Action Example

on:
  push:
    branches:
      - main

jobs:
  github_action_example:
    name: Run GitHub Action
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: install sqruff
        run: cargo install sqruff

      - name: run format checker
        uses: ./
        with:
          context: "./code_to_format"
          config-file: "./code_to_format/.sqruff"
          fail-on-unformatted: "false"
