name: github action example

on:
  push:
    branches:
      - main

jobs:
  github_action_example:
    name: run github action example
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: run format checker
        uses: ./
        with:
          context: "./code_to_format"
          config-file: "./code_to_format/.sqruff"
          fail-on-unformatted: "false"
